# Data exploration <a class="anchor" id="Data_exploration"></a>

The purpose of this notebook is to read data

## Import <a class="anchor" id="Import"></a>

### Prerequisites

- Python >= 3.7
- [numpy](https://pypi.org/project/numpy/)
- [scipy](https://pypi.org/project/scipy/)
- [osfclient](https://pypi.org/project/osfclient/)
- [pandas](https://pypi.org/project/pandas/)
- [pot](https://pypi.org/project/POT/)
- [imbalanced-learn](https://pypi.org/project/imbalanced-learn/)
- [scikit-learn](https://pypi.org/project/scikit-learn/)
- [matplolib](https://pypi.org/project/matplotlib/)
- [jupyter](https://pypi.org/project/jupyter/)


The following cell will install the required pacakge dependencies, if necessary.

In [1]:
import sys
!{sys.executable} -m pip install scikit-learn


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import sparse
import os
import glob

ModuleNotFoundError: No module named 'numpy'

## Loading the meg dataset
### Drive mounting
Begin by mounting the drive where the dataset is located




In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


You should now be able to find the `test` and `train` folders in the `data/` directory
We can now load the training and test data beginning by the training data

### Training dataset
We start by loading the training data.

In [4]:
X_file = os.path.join("/content/gdrive/My Drive/Data/projet_MEG/data/train", "X.csv.gz")
X_train = pd.read_csv(X_file)

# Scale features (avoid tiny numbers)
X_train.iloc[:, :-1] *= 1e12

# Attach LeadField file paths to subjects
lead_pattern = os.path.join("","/content/gdrive/My Drive/Data/projet_MEG/data", "*L.npz")
lead_field_files = sorted(glob.glob(lead_pattern))

# Build mapping: subject → lead field path
lead_subject = {}

for subject in np.unique(X_train["subject"]):
    # Find the leadfield file that contains "<subject>_L"
    matches = [f for f in lead_field_files if f"{subject}_L" in f]

    if not matches:
        raise FileNotFoundError(
              f"Aucun fichier LeadField trouvé pour le sujet {subject}"
        )

    lead_subject[subject] = matches[0]
# Add column of leadfield paths
X_train["L_path"] = X_train["subject"].map(lead_subject)
# Load y
# Load y
y_file = os.path.join("/content/gdrive/My Drive/Data/projet_MEG/data/train", "target.npz")
y_train = sparse.load_npz(y_file).toarray()

In [5]:
# Training data shape
print(X_train.columns)
print(X_train.shape)

Index(['e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9', 'e10',
       ...
       'e197', 'e198', 'e199', 'e200', 'e201', 'e202', 'e203', 'e204',
       'subject', 'L_path'],
      dtype='object', length=206)
(50000, 206)


In [6]:
print(y_train)
y_train.shape

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


(50000, 450)

n_sources_per_sample = np.sum(y_train, axis=1)
print(f'Number of sources in first three samples: {n_sources_per_sample[:3]}')

In [7]:
n_sources_per_sample = np.sum(y_train, axis=1)
print(f'Number of sources in first three samples: {n_sources_per_sample[:3]}')

Number of sources in first three samples: [2. 3. 3.]


### test dataset
Now, it is your turn ! By the same way load the test dataset and start predicting brain areas.


Good luck and have fun with this project.